env:
  global:
    - secure: "bOJasoeROVPsFZ/RotDuC0vuQiWrcE/UrCx6bumbLYv3OyfQqtmBplp4v8xgQLWJgLohwK7wOSBPEh7fquJYC5gpXMlcWa33BYowwAOye3RzLYX3qdqfNzBctLKe/gAv0tgzRY2QopOVHgzhNe5iupebgqAaXLy5hyxhtoFqVaVHSptThHSQVcIIuUfPAq6op5qQUK/1f+0431ZYjuolWoFHCkwoF1i8Tfkk6/blXEGHKHywXhEKY8Nt7101ca2XTgfReFDP4gfLxP7Os2w+2UsBSfDvEObIU4tEw+5brvTid+hzPm8Qovt/ib6/sEXu1Rcu4t8rERpQs6JvVqVZqAx2CInzi7maegMKFZxXQVw/hQe5tAd0AQc5er/IHJ77yVzXfLIS+kEP7yy0Xi0G1nN54Np5+GACKqhcl3QwN5EO2yVZ8nbsezv4UA2MGWmZ6jQzJibIP0SS512ITDUIQeztTX3V54YtcyYc8Aa5L75CtbxPL6LeiIB5Wlp57wB5smaPJEQS4jgGrCJ0y7DHJp7/h1pz3GpFA0SzCPnFY4vnr+CLQDnJ03yIlwTKbgbtzXD9n5CcN6bnToWoTygwKjs+putHwnJgyXVmcMSu3BwKeSWKgHI0mjTZveL8BF9iHnxuz5AatpJg44mE08+U6is6ybjAhRHySu+yoiMdYC8="
language: node_js
node_js:
- '10'
script: npm test
after_success:
  - npm run-script build-all
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    repo: opencrypto-io/schema-explorer
    target_branch: gh-pages
    fqdn: schema.opencrypto.io
  - provider: npm
    email: jan.stransky@arnal.cz
    api_key:
      secure: XwwtGjkSJhJuS/2sYvwZTm9dj7AIAw3471NBXuf4ZdgAFtvlFOjL/I5BbL+38f+b3MVQYpE6fCdL5D0KRDK/PiokgrBNU5yEZoIJ3B8a7BrqOHxJpjxoHxiFOwac4GE9DiQdQtRd07EClxnDByYLLiPwj6/zc3fQjn+GZ4s6/Ly4r359lLnrtDCx/S+HN0geVXjRE38tgzzccEr9Xvq2lh1XNpNf6PUwZCELslIYmcxhjZQM2O2fatFAr7JOGU0iFCbBjknwDxvGVo8vCGg2G2nHVVT4PA0MSGbqg8uIizFAW6EOo3+yLpet9P1j+AQWsx2Os5SE0ID4Mi1lW1MYKFtM410Oor7skYaMnAuY3X5fPdaRAL/l8zwIrBKksJfRw1lBs7OBRc9qgY7LVoGmbK7a17xNj2WdEj33Fho31LIxJsqSVbfqIrk7Kx0UBJy0Yu/qeHSFdgqJwZgmO+RY1z6LIf98r8jW+yOHpRjBwEc9Cd6MRsdL72mo01GSelTcIs7OrJcaz/iTIhty1gAZvWTL+MO4+FqVRZ5DZWY0vLkWsI5hNbGSEUciRxbfMvP7VE410tyWEEUN+XeUH/YnOlQRm3E2eec7dgj92TbxTRFrtmIC0bC+L0x0lJ6xUZ9pQonP3MY8r7+9Qj2kpJMC+8ZbeUwNwrmx0QIsX0+F5PQ=
    on:
      tags: true
      repo: opencrypto-io/schema
