env:
  global:
    - secure: "alX+1SJrEr3X9ksv8Fmm+l6VCzQdQQt1qXnWh6uvDH9oaOa0GABhbu+iInJM9+PMaCwtt/rCvgn5NgRdEYpUpkFdXDXpWHGiaotUFh+Qm31J61Ly4+1K5tDELM3XAa2b67RfJKZc/LYjQuJ7hSU5axSdw+pIvl9PI+dUWCod73YHDZ89LzAelALk4sL0ClNF+zBQ26aEwZ+LNyItIjugO0Z2FYTVQh5BjhzDB3npICdwrN8zDK3CFFNO9s3KSfPx/+1S0uIHQQ4BpFH5166a4cWs06pmVWqR+AXetmBKe2KHCJhdgmLtfiIzhorimRFBAV1YOlocrDPhxThfvbBtYMpIvu+N/03extNrlzU/haMztDaq+UqXbYux00CCw2WdqXwDoDjYPf0gp0NpFLk4L0Sa7hSdpOn3cVTQ6zGYs4/Aufc+q6/JoMdCkLllfSIQsk1pP75lGbJ7E4AbIrfzji2bOIpneumL30Nhj3S3QjYqea53rYM7RsczsK3xxjmbKUal7Lb/sMWzZfwzLaouQGPqQBul4WWmwHDDVgu0FFiwCRQ5JQ0bdwhZ750QeemnhwoPx2yG3TzU2YCSFi4+RVbPLpiBdFIqm3ARu4xDPEY1h0mRd0Wb3/H0DKvL1m28SdkpHAtRBI4Mow31HTZhtJEX6gKhE7UJBOqGJ8q06FA="
language: node_js
node_js:
- '10'
script: npm test
after_success:
  - npm run-script build-all
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    repo: opencrypto-io/schema-explorer
    target_branch: gh-pages
    fqdn: schema.opencrypto.io
  - provider: npm
    email: jan.stransky@arnal.cz
    api_key:
      secure: XwwtGjkSJhJuS/2sYvwZTm9dj7AIAw3471NBXuf4ZdgAFtvlFOjL/I5BbL+38f+b3MVQYpE6fCdL5D0KRDK/PiokgrBNU5yEZoIJ3B8a7BrqOHxJpjxoHxiFOwac4GE9DiQdQtRd07EClxnDByYLLiPwj6/zc3fQjn+GZ4s6/Ly4r359lLnrtDCx/S+HN0geVXjRE38tgzzccEr9Xvq2lh1XNpNf6PUwZCELslIYmcxhjZQM2O2fatFAr7JOGU0iFCbBjknwDxvGVo8vCGg2G2nHVVT4PA0MSGbqg8uIizFAW6EOo3+yLpet9P1j+AQWsx2Os5SE0ID4Mi1lW1MYKFtM410Oor7skYaMnAuY3X5fPdaRAL/l8zwIrBKksJfRw1lBs7OBRc9qgY7LVoGmbK7a17xNj2WdEj33Fho31LIxJsqSVbfqIrk7Kx0UBJy0Yu/qeHSFdgqJwZgmO+RY1z6LIf98r8jW+yOHpRjBwEc9Cd6MRsdL72mo01GSelTcIs7OrJcaz/iTIhty1gAZvWTL+MO4+FqVRZ5DZWY0vLkWsI5hNbGSEUciRxbfMvP7VE410tyWEEUN+XeUH/YnOlQRm3E2eec7dgj92TbxTRFrtmIC0bC+L0x0lJ6xUZ9pQonP3MY8r7+9Qj2kpJMC+8ZbeUwNwrmx0QIsX0+F5PQ=
    on:
      tags: true
      repo: opencrypto-io/schema
